# Generated by Django 5.1 on 2024-09-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_subcategory_options_subcategory_ordering_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('sub_ordering',), 'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='ordering',
            new_name='sub_ordering',
        ),
    ]
