# Generated by Django 5.1 on 2024-09-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'ordering': ('main_ordering',), 'verbose_name_plural': 'Main Categories'},
        ),
        migrations.AddField(
            model_name='maincategory',
            name='main_ordering',
            field=models.IntegerField(default=0),
        ),
    ]
