# Generated by Django 5.1 on 2024-09-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_available',
            field=models.IntegerField(default=1),
        ),
    ]
