# Generated by Django 5.1 on 2024-10-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_subcategory_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_visited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_visits',
            field=models.IntegerField(default=0),
        ),
    ]
