# Generated by Django 5.1 on 2024-11-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_last_visited_product_number_of_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='decrease_by',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='increase_by',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
