# Generated by Django 5.1 on 2024-09-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=50, unique=True)),
                ('coupon_value', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('number_available', models.IntegerField(default=1)),
                ('number_used', models.IntegerField(default=0)),
            ],
        ),
    ]
