# Generated by Django 5.1 on 2024-09-26 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_payment_intent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_intent',
        ),
    ]
