# Generated by Django 5.1 on 2024-09-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_used_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('order_id', models.PositiveIntegerField()),
            ],
        ),
    ]
