# Generated by Django 5.1 on 2024-10-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_remove_order_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='ordered', max_length=20),
        ),
    ]
